name: Build Book

on:
  push:
    # Run on any branch when book content changes
    paths:
      - 'book/**'
      - 'art/**'
      - 'templates/**'
      - 'build.sh'
      - 'tools/**'
      - '.github/workflows/build-book.yml'
      - 'book.yaml'  # Configuration file
  workflow_dispatch:  # Allow manual triggering
    inputs:
      release:
        description: 'Create a release'
        required: false
        type: boolean
        default: false

# Permissions for creating releases and GitHub Pages
permissions:
  contents: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: iksnae/book-builder:latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup book-tools
        run: |
          echo "Setting up book-tools..."
          # Create required directories
          mkdir -p ~/.local/bin
          
          # Clone book-tools repository
          git clone https://github.com/iksnae/book-tools.git ~/.book-tools
          
          # Make scripts executable
          cd ~/.book-tools/src/scripts
          chmod +x *.sh
          
          # Create book-tools command
          echo '#!/bin/bash' > ~/.local/bin/book-tools
          echo 'exec ~/.book-tools/src/scripts/build.sh "$@"' >> ~/.local/bin/book-tools
          chmod +x ~/.local/bin/book-tools
          
          # Add to PATH
          export PATH="$HOME/.local/bin:$PATH"
          echo "export PATH=\"\$HOME/.local/bin:\$PATH\"" >> ~/.bashrc
          
          echo "✅ book-tools installed successfully"
          which book-tools

      - name: Setup book content
        run: |
          echo "Setting up book content..."
          # Create book directory structure in ~/.book-tools
          mkdir -p ~/.book-tools/book/en
          mkdir -p ~/.book-tools/resources/images
          
          # Copy book content if it exists
          if [ -d "$GITHUB_WORKSPACE/book" ]; then
            echo "Copying book content..."
            cp -r $GITHUB_WORKSPACE/book/* ~/.book-tools/book/ || echo "Warning: Some files could not be copied"
          else
            echo "Creating book directory structure..."
            mkdir -p ~/.book-tools/book/en
          fi
          
          # Copy book.yaml if it exists
          if [ -f "$GITHUB_WORKSPACE/book.yaml" ]; then
            echo "Copying book.yaml..."
            cp $GITHUB_WORKSPACE/book.yaml ~/.book-tools/
          else
            echo "Warning: book.yaml not found"
          fi
          
          # Copy images from various possible locations
          echo "Copying images..."
          if [ -d "$GITHUB_WORKSPACE/art" ]; then
            echo "Copying from art directory..."
            cp -r $GITHUB_WORKSPACE/art/* ~/.book-tools/resources/images/ || echo "Warning: Some art files could not be copied"
          fi
          
          if [ -d "$GITHUB_WORKSPACE/book/images" ]; then
            echo "Copying from book/images directory..."
            cp -r $GITHUB_WORKSPACE/book/images/* ~/.book-tools/resources/images/ || echo "Warning: Some book images could not be copied"
          fi
          
          if [ -d "$GITHUB_WORKSPACE/book/en/images" ]; then
            echo "Copying from book/en/images directory..."
            cp -r $GITHUB_WORKSPACE/book/en/images/* ~/.book-tools/resources/images/ || echo "Warning: Some English images could not be copied"
          fi
          
          echo "Book content:"
          ls -la ~/.book-tools/book/ || echo "Book directory is empty"
          echo "Book config:"
          cat ~/.book-tools/book.yaml || echo "No book.yaml found"
          echo "Images:"
          ls -la ~/.book-tools/resources/images/ || echo "No images found"

      - name: Build book
        run: |
          echo "Building book with book-tools..."
          export PATH="$HOME/.local/bin:$PATH"
          cd ~/.book-tools
          pwd
          ls -la
          book-tools build --verbose
          
          # Copy built files back to workspace
          mkdir -p $GITHUB_WORKSPACE/build
          cp -r ~/.book-tools/build/* $GITHUB_WORKSPACE/build/

      - name: List build directory contents
        run: |
          echo "=== Build Directory Contents ==="
          cd $GITHUB_WORKSPACE
          ls -la build/ || echo "Build directory not found"
          
          echo "=== ES Directory Contents ==="
          ls -la build/es/ || echo "ES directory may not exist yet"
          
          echo "=== Book File Sizes ==="
          find build/ -type f \( -name "*.pdf" -o -name "*.epub" -o -name "*.mobi" -o -name "*.html" -o -name "*.docx" \) -exec du -h {} \; 2>/dev/null || echo "Some files may be missing"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-files
          path: |
            build/*.pdf
            build/*.epub
            build/*.mobi
            build/*.html
            build/*.md
            build/*.docx
            build/es/**
            build/images/**