name: Test Book Tools

on:
  push:
    branches: [ main, 'fix/*', 'feature/*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: iksnae/book-builder:latest

    steps:
      - uses: actions/checkout@v4

      - name: Load configuration
        run: |
          if [ -f "book.yaml" ]; then
            echo "Using configuration from book.yaml"
            # Extract book title
            BOOK_TITLE=$(grep 'title:' book.yaml | head -n 1 | cut -d':' -f2- | sed 's/^[ \t]*//' | sed 's/\"//g')
            echo "BOOK_TITLE=$BOOK_TITLE" >> $GITHUB_ENV
            
            # Extract book author
            BOOK_AUTHOR=$(grep 'author:' book.yaml | head -n 1 | cut -d':' -f2- | sed 's/^[ \t]*//' | sed 's/\"//g')
            echo "BOOK_AUTHOR=$BOOK_AUTHOR" >> $GITHUB_ENV
          else
            echo "No book.yaml found, using default values"
            echo "BOOK_TITLE=My Book" >> $GITHUB_ENV
            echo "BOOK_AUTHOR=Author Name" >> $GITHUB_ENV
          fi
          
          # Print the configuration values for debugging
          echo "Book Title: $BOOK_TITLE"
          echo "Book Author: $BOOK_AUTHOR"

      - name: Setup test environment
        run: |
          mkdir -p build

          # Create language directories based on what exists in the book/ folder
          for lang in $(ls -1 book/ 2>/dev/null || echo "en"); do
            if [ -d "book/$lang" ] && [ "$lang" != "images" ]; then
              echo "Creating build directory for language: $lang"
              mkdir -p "build/$lang"
            fi
          done

          # Fix permissions on script files
          chmod +x src/scripts/*.sh

      - name: Build book
        run: |
          echo "Building book..."
          src/scripts/build.sh --verbose