name: Build Book

on:
  push:
    branches: [ main, 'fix/*', 'feature/*' ]
    paths:
      - 'book/**'
      - 'src/**'
      - 'book.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'book/**'
      - 'src/**'
      - 'book.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: iksnae/book-builder:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build book
        run: |
          # Make scripts executable
          chmod +x src/scripts/*.sh

          # Run build with verbose output
          src/scripts/build.sh --verbose --all-languages

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-outputs
          path: build/**/*.*
          if-no-files-found: error